ALTER TABLE `project-tcc-434118.BRONZE_ATD_CSR.tb_interactions`
ADD COLUMN IF NOT EXISTS DT_PROCESSAMENTO STRING;
 
UPDATE `project-tcc-434118.BRONZE_ATD_CSR.tb_interactions`
SET DT_PROCESSAMENTO = '{date}'
WHERE DT_PROCESSAMENTO IS NULL